// seoKeywords.ts

const seoKeywords = [
  "Cycle Safari",
  "Cycling holidays in Central India",
  "Central India cycling tours",
  "Cycling tours in Nagpur",
  "Pench cycling safari",
  "Satpura cycling adventure",
  "Kanha cycling tours",
  "Multi-day cycling tours India",
  "Guided cycling tours India",
  "Wildlife cycling tours India",
  "Overnight cycling camping trips in India",
  "Sub-24 hour overnight bike camping (S24O)",
  "Cycling tours near Pench National Park",
  "Cycling holidays in Madhya Pradesh",
  "Cycling tours in Satpura hills",
  "Cycling adventures in Central India",
  "Cycling tours in Kanha National Park",
  "Cycling tours in Pench National Park",
  "Cycling tours in Chikhaldara",
  "Cycling tours in Pachmarhi",
  "Cycling tours in Satpuda",
  "Cycling tours in Nagpur",
  "Cycling tours in Maharashtra",
  "Cycling tours in Madhya Pradesh",
  "Cycling tours in India",
  "Cycling tours in Central India",
  "Cycling tours in forests of India",
  "Cycling tours in wildlife sanctuaries of India",
  "Cycling tours in national parks of India",
  "Cycling tours in buffer zones of national parks",
  "Cycling tours in tribal villages of India",
  "Cycling tours in rural India",
  "Cycling tours in offbeat locations of India",
  "Cycling tours in scenic landscapes of India",
  "Cycling tours in hilly terrains of India",
  "Cycling tours in forested corridors of India",
  "Cycling tours in biodiversity hotspots of India",
  "Cycling tours in cultural heritage sites of India",
  "Cycling tours in eco-tourism destinations of India",
  "Cycling tours in sustainable tourism destinations of India",
  "Cycling tours in adventure tourism destinations of India",
  "Cycling tours in nature tourism destinations of India",
  "Cycling tours in responsible tourism destinations of India",
  "Cycling tours in experiential tourism destinations of India",
  "Cycling tours in immersive tourism destinations of India",
  "Cycling tours in authentic tourism destinations of India",
  "Cycling tours in off-the-beaten-path destinations of India",
  "Cycling tours in hidden gems of India",
  "Cycling tours in unexplored destinations of India",
  "Cycling tours in lesser-known destinations of India",
  "Cycling tours in remote destinations of India",
  "Cycling tours in secluded destinations of India",
  "Cycling tours in tranquil destinations of India",
  "Cycling tours in serene destinations of India",
  "Cycling tours in peaceful destinations of India",
  "Cycling tours in calm destinations of India",
  "Cycling tours in quiet destinations of India",
  "Cycling tours in relaxing destinations of India",
  "Cycling tours in rejuvenating destinations of India",
  "Cycling tours in refreshing destinations of India",
  "Cycling tours in invigorating destinations of India",
  "Cycling tours in energizing destinations of India",
  "Cycling tours in revitalizing destinations of India",
  "Cycling tours in recharging destinations of India",
  "Cycling tours in inspiring destinations of India",
  "Cycling tours in motivating destinations of India",
  "Cycling tours in uplifting destinations of India",
  "Cycling tours in exhilarating destinations of India",
  "Cycling tours in thrilling destinations of India",
  "Cycling tours in exciting destinations of India",
  "Cycling tours in adventurous destinations of India",
  "Cycling tours in challenging destinations of India",
  "Cycling tours in demanding destinations of India",
  "Cycling tours in strenuous destinations of India",
  "Cycling tours in tough destinations of India",
  "Cycling tours in rugged destinations of India",
  "Cycling tours in rough destinations of India",
  "Cycling tours in bumpy destinations of India",
  "Cycling tours in uneven destinations of India",
  "Cycling tours in hilly destinations of India",
  "Cycling tours in mountainous destinations of India",
  "Cycling tours in valley destinations of India",
  "Cycling tours in plateau destinations of India",
  "Cycling tours in plain destinations of India",
  "Cycling tours in coastal destinations of India",
  "Cycling tours in desert destinations of India",
  "Cycling tours in riverine destinations of India",
  "Cycling tours in wetland destinations of India",
  "Cycling tours in grassland destinations of India",
  "Cycling tours in savanna destinations of India",
  "Cycling tours in tundra destinations of India",
  "Cycling tours in taiga destinations of India",
  "Cycling tours in rainforest destinations of India",
  "Cycling tours in monsoon forest destinations of India",
  "Cycling tours in deciduous forest destinations of India",
  "Cycling tours in evergreen forest destinations of India",
  "Cycling tours in coniferous forest destinations of India",
  "Cycling tours in mixed forest destinations of India",
  "Cycling tours in mangrove forest destinations of India",
  "Cycling tours in swamp forest destinations of India",
  "Cycling tours in cloud forest destinations of India",
  "Cycling tours in montane forest destinations of India",
  "Cycling tours in tropical forest destinations of India",
  "Cycling tours in subtropical forest destinations of India",
  "Cycling tours in temperate forest destinations of India",
  "Cycling tours in boreal forest destinations of India",
];

export default seoKeywords;
